# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synchronizerd.ui'
#
# Created: Mon Nov 11 18:17:56 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SyncMain(object):
    def setupUi(self, SyncMain):
        SyncMain.setObjectName("SyncMain")
        SyncMain.resize(340, 361)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("synchronizer-rd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SyncMain.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SyncMain)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.textFrom = QtGui.QLineEdit(self.centralwidget)
        self.textFrom.setObjectName("textFrom")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.textFrom)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.textTo = QtGui.QLineEdit(self.centralwidget)
        self.textTo.setObjectName("textTo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.textTo)
        self.horizontalLayout.addLayout(self.formLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btOpenFrom = QtGui.QPushButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("openfolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btOpenFrom.setIcon(icon1)
        self.btOpenFrom.setObjectName("btOpenFrom")
        self.gridLayout.addWidget(self.btOpenFrom, 0, 0, 1, 1)
        self.btOpenTo = QtGui.QPushButton(self.centralwidget)
        self.btOpenTo.setIcon(icon1)
        self.btOpenTo.setObjectName("btOpenTo")
        self.gridLayout.addWidget(self.btOpenTo, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.textStatus = QtGui.QTextEdit(self.centralwidget)
        self.textStatus.setObjectName("textStatus")
        self.gridLayout_2.addWidget(self.textStatus, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btSync = QtGui.QPushButton(self.centralwidget)
        self.btSync.setBaseSize(QtCore.QSize(0, 0))
        self.btSync.setObjectName("btSync")
        self.horizontalLayout_2.addWidget(self.btSync)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        SyncMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SyncMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 340, 19))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        SyncMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SyncMain)
        self.statusbar.setObjectName("statusbar")
        SyncMain.setStatusBar(self.statusbar)
        self.actionOpen_Folder_From = QtGui.QAction(SyncMain)
        self.actionOpen_Folder_From.setObjectName("actionOpen_Folder_From")
        self.actionOpen_Folder_To = QtGui.QAction(SyncMain)
        self.actionOpen_Folder_To.setObjectName("actionOpen_Folder_To")
        self.action_Exit = QtGui.QAction(SyncMain)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtGui.QAction(SyncMain)
        self.action_About.setObjectName("action_About")
        self.actionAbout_Qt = QtGui.QAction(SyncMain)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.action_License = QtGui.QAction(SyncMain)
        self.action_License.setObjectName("action_License")
        self.actionSend_Feedback = QtGui.QAction(SyncMain)
        self.actionSend_Feedback.setObjectName("actionSend_Feedback")
        self.actionMake_someone_happy = QtGui.QAction(SyncMain)
        self.actionMake_someone_happy.setObjectName("actionMake_someone_happy")
        self.menu_File.addAction(self.actionOpen_Folder_From)
        self.menu_File.addAction(self.actionOpen_Folder_To)
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionAbout_Qt)
        self.menu_Help.addAction(self.action_License)
        self.menu_Help.addAction(self.actionSend_Feedback)
        self.menu_Help.addAction(self.actionMake_someone_happy)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(SyncMain)
        QtCore.QMetaObject.connectSlotsByName(SyncMain)

    def retranslateUi(self, SyncMain):
        SyncMain.setWindowTitle(QtGui.QApplication.translate("SyncMain", "SynchronizeRD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SyncMain", "Synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SyncMain", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SyncMain", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.btOpenFrom.setText(QtGui.QApplication.translate("SyncMain", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.btOpenTo.setText(QtGui.QApplication.translate("SyncMain", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SyncMain", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.btSync.setText(QtGui.QApplication.translate("SyncMain", "Synchronize!", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("SyncMain", "&Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("SyncMain", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Folder_From.setText(QtGui.QApplication.translate("SyncMain", "Open Folder &From", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Folder_To.setText(QtGui.QApplication.translate("SyncMain", "Open Folder &To", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("SyncMain", "&Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(QtGui.QApplication.translate("SyncMain", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("SyncMain", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.action_License.setText(QtGui.QApplication.translate("SyncMain", "&License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSend_Feedback.setText(QtGui.QApplication.translate("SyncMain", "Send &Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMake_someone_happy.setText(QtGui.QApplication.translate("SyncMain", "Make Someone &Happy", None, QtGui.QApplication.UnicodeUTF8))

